### ISSUE TITLE
Add recurrent network implementation

### ISSUE THREAD

**Issue by benoitfragit** [benoitfragit/MultiLayerPerceptron#33]
see 
http://www.wildml.com/2015/09/recurrent-neural-networks-tutorial-part-2-implementing-a-language-model-rnn-with-python-numpy-and-theano/

Or

http://karpathy.github.io/2015/05/21/rnn-effectiveness/

**Comment by benoitfragit** [comment]
See
iamtrask.github.io/2015/11/15/anyone-can

**Comment by benoitfragit** [comment]
Best way to do it is to introduce a new output to the type Layer ie a new buffer. 

This buffer will be use for self connection in recurrent Network.

We also need to use a Network mode to decide whether or not the network should be unrolled or directly connected to itself.

In offline mode we should use a bptt lenght loaded from xml settings and use it to create an unrolled network. For each input sequence, each position represent a time step and should be passed to the network.

**Comment by benoitfragit** [comment]
The better article I found is : 

https://medium.com/@aidangomez/let-s-do-this-f9b699de31d9

**Comment by benhizia** [comment]
Nicely done !
